# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno and run tests across stable and nightly builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denolib/setup-deno

name: Build and Deploy

on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Prepare and deploy
      env:
        GITHUB_TOKEN: SHA256:qK2PuGso5dA95xjcEI6ZnX1caMeSm8gtJ1vHV31wpyk
      run: |
        npm install
        npm run ng -- deploy --base-href=/Sudoku/ --name="sarthak-mittal" --email="sarthakmittal20@gmail.com" --no-silent
